### PR TITLE
added a question about streaming error and success branches separately

### PR DESCRIPTION
**Pull request by kwijibo**

### CODE REVIEW

**Comment by dominictarr** [comment]
thanks!

**Comment by dominictarr** [comment]
oh oops, I misunderstood what your PR was (thought it was just a markdown typo)

the answer to your question - can I fork a pull-stream, yes but that isn't how you'd solve the problem you mention. pull-streams do not have an error stream. If there is an error, it terminates the stream. I think if you use `pull(yourStream, require('pull-stdio').stdout())` then if the stream errors, it will throw, which will print the stack trace to stdout. Does this solve your problem?

**Comment by kwijibo** [comment]
>  if you use pull(yourStream, require('pull-stdio').stdout()) then if the stream errors, it will throw, which will print the stack trace to stdout. Does this solve your problem?

It would if it did :)

```
    const dir = process.argv[2]
    pull(
        file(path.join(dir, 'index.txt')),
        stdio.stdout()
    )
```
If I give this script the right directory, it prints the contents of the file and gives an exit code `0`, which is great, but if I give it a non-existent directory name as an argument, it just outputs nothing, again with a `0` exit code.

However I can use `pull-catch` 
```
pull(
    source, 
    pullCatch(err => {
       process.stderr.write(String(err)+'\n')
       process.exit(1)
    }),
    sink
)
```
I think I was hoping for something neat like `fork(stdio.stderr(), stdio.stdout())`, but I take your point that pull-streams are designed to terminate on error.

**Comment by dominictarr** [comment]
I've opened an issue on pull-stdio, although normally sinks should take a callback which called when the end or error, and pull-stdio does this, so you can do

``` js
pull(source, stdio.stdout(function (err) { if(err) throw err }))
```

**Comment by kwijibo** [comment]
thanks for the feedback

**Pull request merged**
